#ddev-generated
version: '3.6'
services:
  typesense:
    container_name: ddev-${DDEV_SITENAME}-typesense
    hostname: ${DDEV_SITENAME}-typesense
    image: typesense/typesense:0.23.1
    expose:
      - "8108"
    command: tail -f /dev/null
    networks: [default, ddev_default]
    restart: "no"
    environment:
      - VIRTUAL_HOST=$DDEV_HOSTNAME
      - HTTP_EXPOSE=8108:8108
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_API_KEY=writeable-api
    # These labels ensure this service is discoverable by ddev.
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

    volumes:
      - "./typesense:/data"
